# Generated by Django 6.0.2 on 2026-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_image_url_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='Jadikan Banner Slider'),
        ),
    ]
