# Generated by Django 6.0.2 on 2026-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nexus IT', max_length=100, verbose_name='Nama Website')),
                ('whatsapp_number', models.CharField(help_text='Gunakan format 628xxx (tanpa + atau 0 di depan)', max_length=20, verbose_name='No WhatsApp Admin')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Link Instagram')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat Toko')),
            ],
            options={
                'verbose_name': 'Pengaturan Website',
                'verbose_name_plural': 'Pengaturan Website',
            },
        ),
    ]
